SECTION_2_4 = {
    "title": "2.4 CONDICIONES DE ACCESIBILIDAD DISCAPACIDAD SENSORIAL (VISUAL-AUDITIVA)",
    "accesible_options": ["No", "Si", "Parcial"],
    "questions": [
        {
            "id": "senalizacion_orientacion",
            "label": "¿Se cuenta con señalización de orientación y movilidad?",
            "type": "lista",
            "has_accesible": True,
            "options": [
                "Cuenta con señalización en el área operativa.",
                "Cuenta con señalización en el área administrativa.",
                "Cuenta con señalización en ambas áreas.",
                "No aplica.",
            ],
        },
        {
            "id": "senalizacion_emergencia",
            "label": "¿Se cuenta con señalización de emergencia?",
            "type": "lista",
            "has_accesible": True,
            "options": [
                "Cuenta con señalización en el área operativa.",
                "Cuenta con señalización en el área administrativa.",
                "Cuenta con señalización en ambas áreas.",
                "No aplica.",
            ],
        },
        {
            "id": "distribucion_zonas_comunes",
            "label": (
                "¿La distribución de las zonas comunes (cafetería, oficinas, entre otras) "
                "permite una fácil orientación y guía espacial?"
            ),
            "type": "accesible_con_observaciones",
            "has_accesible": True,
        },
        {
            "id": "senalizacion_mapa_evacuacion",
            "label": (
                "¿La señalización de mapa evacuación garantiza que pueda comprender y orientarse "
                "de manera autónoma y segura, \"relieve-colores, apoyo auditivo\"?"
            ),
            "type": "accesible_con_observaciones",
            "has_accesible": True,
        },
        {
            "id": "ascensor_apoyo_visual_sonoro",
            "label": "¿El ascensor al interior de las instalaciones cuenta con apoyo visual y sonoro?",
            "type": "accesible_con_observaciones",
            "has_accesible": True,
        },
        {
            "id": "apoyo_seguridad_ubicacion",
            "label": "¿Se cuenta con apoyo de seguridad para la ubicación dentro de las instalaciones?",
            "type": "accesible_con_observaciones",
            "has_accesible": True,
        },
        {
            "id": "senalizacion_ntc",
            "label": "¿La señalización cumple con los criterios de la NTC?",
            "type": "lista_multiple",
            "has_accesible": True,
            "options": [
                "La señalización cumple con los criterios de material de acuerdo a la NTC.",
                "La señalización No cumple con los criterios de material de acuerdo a la NTC.",
                "No aplica.",
            ],
            "options_secondary": [
                "La señalización cumple con los criterios de accesibilidad (Braille, LSC, "
                "pictograma y letras) de acuerdo a la NTC.",
                "La señalización No cumple con los criterios de accesibilidad (Braille, LSC, "
                "pictograma y letras) de acuerdo a la NTC.",
                "No se cuenta con señalización de orientación.",
                "No aplica.",
            ],
        },
        {
            "id": "mapa_evacuacion_ntc",
            "label": "¿El mapa de evacuación cumple con criterios de accesibilidad de la NTC?",
            "type": "lista_multiple",
            "has_accesible": True,
            "options": [
                "Cuenta con señalización en el área operativa.",
                "Cuenta con señalización en el área administrativa.",
                "Cuenta con señalización en ambas áreas.",
                "No aplica.",
            ],
            "options_secondary": [
                "La señalización cumple con los criterios de material de acuerdo a la NTC.",
                "La señalización No cumple con los criterios de material de acuerdo a la NTC.",
                "No aplica.",
            ],
            "options_tertiary": [
                "La señalización cumple con los criterios de accesibilidad (Braille, LSC, "
                "pictograma y letras) de acuerdo a la NTC.",
                "La señalización No cumple con los criterios de accesibilidad (Braille, LSC, "
                "pictograma y letras) de acuerdo a la NTC.",
                "No se cuenta con señalización de orientación.",
                "No aplica.",
            ],
        },
        {
            "id": "informacion_accesible_ingreso",
            "label": "¿Se suministra información accesible al ingreso de la empresa?",
            "type": "lista_multiple",
            "has_accesible": True,
            "options": [
                "El nombre de la empresa es visible desde el exterior.",
                "El nombre de la empresa No es visible desde el exterior.",
                "No aplica.",
            ],
            "options_secondary": [
                "La nomenclatura (número de bodega, dirección) de la empresa es visible desde el exterior.",
                "La nomenclatura (número de bodega, dirección) de la empresa No es visible desde el exterior.",
                "No aplica.",
            ],
            "options_tertiary": [
                "El timbre cuenta con apoyo auditivo.",
                "El timbre cuenta con apoyo visual.",
                "El timbre cuenta con apoyo visual y auditivo.",
                "Cuenta con timbre pero no es accesible para PCD.",
                "No aplica.",
            ],
            "options_quaternary": [
                "La empresa cuenta con citofono.",
                "La empresa No cuenta con citofono.",
                "No aplica.",
                "La empresa cuenta con teléfono anuncio ingreso",
            ],
        },
        {
            "id": "medios_tecnologicos_ingreso",
            "label": (
                "¿La empresa hace uso de medios tecnológicos para el ingreso? "
                "(Tablet, lector facial, biométrico)"
            ),
            "type": "accesible_con_observaciones",
            "has_accesible": True,
        },
        {
            "id": "material_seleccion_accesible",
            "label": "¿El material utilizado en el proceso de selección es accesible?",
            "type": "lista_multiple",
            "has_accesible": True,
            "options": [
                "Cuenta con subtítulos y LSC.",
                "No cuenta con subtítulos y LSC.",
                "No aplica.",
                "Cuenta con LSC y no tiene apoyo de subtítulos.",
                "Cuenta con subtítulos y no apoyo de LSC.",
            ],
            "options_secondary": [
                "Cuenta con audiodescripción y sistema braille.",
                "No cuenta con audiodescripción y sistema braille.",
                "No aplica.",
                "Cuenta con audiodescripción y no cuenta con sistema braille.",
                "No cuenta con audiodescripción y cuenta con sistema braille.",
            ],
            "options_tertiary": [
                "Cuenta con vídeos, imágenes y pictogramas.",
                "No cuenta con vídeos, imágenes y pictogramas.",
                "No aplica.",
                "Cuenta con vídeos.",
                "Cuenta con vídeos e imágenes.",
                "Cuenta con vídeos y pictogramas.",
                "Cuenta con imágenes.",
                "Cuenta con imágenes y pictogramas.",
                "Cuenta con pictogramas.",
            ],
        },
        {
            "id": "material_contratacion_accesible",
            "label": "¿El material utilizado en el proceso de contratación es accesible?",
            "type": "lista_multiple",
            "has_accesible": True,
            "options": [
                "Cuenta con audiodescripción y sistema braille.",
                "No cuenta con audiodescripción y sistema braille.",
                "No aplica.",
                "Cuenta con audiodescripción y no cuenta con sistema braille.",
                "No cuenta con audiodescripción y cuenta con sistema braille.",
            ],
            "options_secondary": [
                "Cuenta con vídeos, imágenes y pictogramas.",
                "No cuenta con vídeos, imágenes y pictogramas.",
                "No aplica.",
                "Cuenta con vídeos.",
                "Cuenta con vídeos e imágenes.",
                "Cuenta con vídeos y pictogramas.",
                "Cuenta con imágenes.",
                "Cuenta con imágenes y pictogramas.",
                "Cuenta con pictogramas.",
            ],
        },
        {
            "id": "material_induccion_accesible",
            "label": "¿El material utilizado en el proceso de inducción y reinducción es accesible?",
            "type": "lista_multiple",
            "has_accesible": True,
            "options": [
                "Cuenta con subtítulos y LSC.",
                "No cuenta con subtítulos y LSC.",
                "No aplica.",
                "Cuenta con LSC y no tiene apoyo de subtítulos.",
                "Cuenta con subtítulos y no apoyo de LSC.",
            ],
            "options_secondary": [
                "Cuenta con audiodescripción y sistema braille.",
                "No cuenta con audiodescripción y sistema braille.",
                "No aplica.",
                "Cuenta con audiodescripción y no cuenta con sistema braille.",
                "No cuenta con audiodescripción y cuenta con sistema braille.",
            ],
            "options_tertiary": [
                "Cuenta con vídeos, imágenes y pictogramas.",
                "No cuenta con vídeos, imágenes y pictogramas.",
                "No aplica.",
                "Cuenta con vídeos.",
                "Cuenta con vídeos e imágenes.",
                "Cuenta con vídeos y pictogramas.",
                "Cuenta con imágenes.",
                "Cuenta con imágenes y pictogramas.",
                "Cuenta con pictogramas.",
            ],
        },
        {
            "id": "material_evaluacion_desempeno",
            "label": "¿El material utilizado en el proceso de evaluación del desempeño es accesible?",
            "type": "lista_multiple",
            "has_accesible": True,
            "options": [
                "Cuenta con subtítulos y LSC.",
                "No cuenta con subtítulos y LSC.",
                "No aplica.",
                "Cuenta con LSC y no tiene apoyo de subtítulos.",
                "Cuenta con subtítulos y no apoyo de LSC.",
            ],
            "options_secondary": [
                "Cuenta con audiodescripción y sistema braille.",
                "No cuenta con audiodescripción y sistema braille.",
                "No aplica.",
                "Cuenta con audiodescripción y no cuenta con sistema braille.",
                "No cuenta con audiodescripción y cuenta con sistema braille.",
            ],
            "options_tertiary": [
                "Cuenta con vídeos, imágenes y pictogramas.",
                "No cuenta con vídeos, imágenes y pictogramas.",
                "No aplica.",
                "Cuenta con vídeos.",
                "Cuenta con vídeos e imágenes.",
                "Cuenta con vídeos y pictogramas.",
                "Cuenta con imágenes.",
                "Cuenta con imágenes y pictogramas.",
                "Cuenta con pictogramas.",
            ],
        },
        {
            "id": "plataformas_autogestion",
            "label": "¿La organización cuenta con plataformas de autogestión?",
            "type": "lista_multiple",
            "has_accesible": True,
            "options": [
                "Trámites administrativos.",
                "Proceso de autocapacitación.",
                "Trámites administrativos y proceso de autocapacitación.",
                "No aplica.",
            ],
            "options_secondary": [
                "Cuenta con subtítulos y LSC.",
                "No cuenta con subtítulos y LSC.",
                "No aplica.",
                "Cuenta con LSC y no tiene apoyo de subtítulos.",
                "Cuenta con subtítulos y no apoyo de LSC.",
            ],
            "options_tertiary": [
                "Cuenta con audiodescripción y sistema braille.",
                "No cuenta con audiodescripción y sistema braille.",
                "No aplica.",
                "Cuenta con audiodescripción y no cuenta con sistema braille.",
                "No cuenta con audiodescripción y cuenta con sistema braille.",
            ],
            "options_quaternary": [
                "Cuenta con vídeos, imágenes y pictogramas.",
                "No cuenta con vídeos, imágenes y pictogramas.",
                "No aplica.",
                "Cuenta con vídeos.",
                "Cuenta con vídeos e imágenes.",
                "Cuenta con vídeos y pictogramas.",
                "Cuenta con imágenes.",
                "Cuenta con imágenes y pictogramas.",
                "Cuenta con pictogramas.",
            ],
        },
        {
            "id": "alarma_emergencia",
            "label": "¿La empresa cuenta con alarma de emergencia accesible?",
            "type": "lista",
            "has_accesible": True,
            "options": [
                "Cuenta con solo alarma auditiva.",
                "Cuenta con solo alarma visual.",
                "Cuenta con alarma auditiva y visual.",
                "No aplica.",
            ],
        },
        {
            "id": "ajustes_razonables_individualizados",
            "label": "¿La organización cuenta con la posibilidad de hacer ajustes razonables individualizados?",
            "type": "lista",
            "has_accesible": True,
            "options": [
                "Cuenta con la posibilidad de flexibilizar rutinas laborales.",
                "No cuenta con la posibilidad de flexibilizar rutinas laborales.",
                "No aplica.",
            ],
            "text_observaciones": True,
        },
    ],
}
